server:
  port: 8999
  servlet:
    encoding:
      force-response: true


spring:
  application:
    name: unite-gateway
  profiles:
    active: @activatedProperties@  #开发环境(DEV)   测试环境(FAT)  用户验收(UAT) 生产环境(PROD)
  cloud:
    nacos:
      discovery:
        server-addr: http://test-nacos.juzishuke.com:8848
        group: JZHL_JDD-QDM_GROUP
        namespace: jzhl_dev1
        password: nacos
        username: nacos



